// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package epg_jsoner

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6a975c40DecodeOttPlayEpgConverterLibEpgJsoner(in *jlexer.Lexer, out *EpgRecord) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "time":
			out.Time = uint64(in.Uint64())
		case "time_to":
			out.TimeTo = uint64(in.Uint64())
		case "descr":
			if in.IsNull() {
				in.Skip()
				out.Descr = nil
			} else {
				if out.Descr == nil {
					out.Descr = new(string)
				}
				*out.Descr = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeOttPlayEpgConverterLibEpgJsoner(out *jwriter.Writer, in EpgRecord) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Time))
	}
	{
		const prefix string = ",\"time_to\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.TimeTo))
	}
	{
		const prefix string = ",\"descr\":"
		out.RawString(prefix)
		if in.Descr == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Descr))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EpgRecord) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeOttPlayEpgConverterLibEpgJsoner(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EpgRecord) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeOttPlayEpgConverterLibEpgJsoner(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EpgRecord) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeOttPlayEpgConverterLibEpgJsoner(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EpgRecord) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeOttPlayEpgConverterLibEpgJsoner(l, v)
}
func easyjson6a975c40DecodeOttPlayEpgConverterLibEpgJsoner1(in *jlexer.Lexer, out *EpgData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "epg_data":
			if in.IsNull() {
				in.Skip()
				out.EpgData = nil
			} else {
				in.Delim('[')
				if out.EpgData == nil {
					if !in.IsDelim(']') {
						out.EpgData = make([]EpgRecord, 0, 1)
					} else {
						out.EpgData = []EpgRecord{}
					}
				} else {
					out.EpgData = (out.EpgData)[:0]
				}
				for !in.IsDelim(']') {
					var v1 EpgRecord
					(v1).UnmarshalEasyJSON(in)
					out.EpgData = append(out.EpgData, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6a975c40EncodeOttPlayEpgConverterLibEpgJsoner1(out *jwriter.Writer, in EpgData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"epg_data\":"
		out.RawString(prefix[1:])
		if in.EpgData == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.EpgData {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EpgData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6a975c40EncodeOttPlayEpgConverterLibEpgJsoner1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EpgData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6a975c40EncodeOttPlayEpgConverterLibEpgJsoner1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EpgData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6a975c40DecodeOttPlayEpgConverterLibEpgJsoner1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EpgData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6a975c40DecodeOttPlayEpgConverterLibEpgJsoner1(l, v)
}
